import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import SearchExercise from '../components/SearchExercises'
export default function Home() {
  return (
    <div>
      <Head>
        <title>MuscleUP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <SearchExercise />
     
    </div>
  )
}
